### ISSUE TITLE
This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

### ISSUE THREAD

**Issue by RobotCherries** [ragtam/yt-player-angular#11]
Hello, I'm facing the following issues when trying to install this **yt-player** & **yt-player-angular** with Angular **version 11.0.9**, using **strict mode**.

I've already tried setting the following flags to true, but it still won't work. Got any ideas on how to fix this?
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,

![image](https://user-images.githubusercontent.com/26595540/108681386-c4a7af80-74f7-11eb-830a-959ea91173b1.png)

Thanks!

**Comment by ragtam** [comment]
Hello, thanks for feedback. I`ll try to reproduce and check what can be done. Cheers!

**Comment by ragtam** [comment]
Took some time, but now it should be fixed.
